[workspace]
members = [
    "abop-core",
    "abop-gui",
    "abop-cli"
]
resolver = "2"



[workspace.dependencies]
# Core Dependencies - pinned for stability
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
serde = { version = "1.0", features = ["derive", "rc"] }
toml = "0.8"
chrono = { version = "0.4", features = ["serde", "clock", "std"] }
uuid = { version = "1.0", features = ["v4", "serde", "v7"] }
once_cell = "1.0"

# Common Dependencies - pinned versions
bitflags = "2.9.1"  # Latest stable version
cfg_aliases = "0.2.1"  # Corrected name
fontdb = "0.18.0"  # Latest stable version
getrandom = "0.3.3"  # Latest stable version
hashbrown = "0.15.3"  # Latest stable version
kurbo = "0.11.2"  # Latest stable version
libloading = "0.8.8"  # Latest stable version

# File System & Database - pinned versions
dirs = "5.0"
walkdir = "2.4"
rusqlite = { version = "0.36.0", features = ["bundled", "chrono"] }
r2d2 = "0.8.10"
r2d2_sqlite = "0.29.0"

# Async Runtime - pinned versions
futures = "0.3"
tokio = { version = "1.37", features = ["full"] }
async-trait = "0.1"
tokio-util = "0.7"
tokio-stream = "0.1"

# Audio Processing - specific versions for compatibility
symphonia = { version = "0.5.4", features = ["mp3", "aac", "isomp4", "flac", "all-codecs", "all-formats", "opt-simd"] }
rodio = { version = "0.17", features = ["symphonia"] }
num-complex = "0.4"
hound = "3.0"
rayon = "1.0"

# File dialogs - pinned version
rfd = "0.14"

# Utilities - pinned versions
bytemuck = { version = "1.0", features = ["derive", "extern_crate_alloc"] }
serde_json = "1.0"
rand = "0.9.1"  # Pinned to match core crate
humantime-serde = "1.1"

# Development dependencies
tempfile = "3.8"  # For tests
criterion = { version = "0.5", features = ["html_reports"] }
approx = "0.5.1"  # For floating-point comparisons in tests



[workspace.lints.clippy]


# Promote important lints to warnings (keeping best practices)
missing_errors_doc = "warn"
missing_panics_doc = "warn"
must_use_candidate = "warn"
doc_markdown = "warn"
float_cmp = "warn"
cast_precision_loss = "warn"
cast_possible_truncation = "warn"
cast_sign_loss = "warn"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Your Name <your.email@example.com>"]
description = "Audiobook Organizer & Processor"
license = "MIT"
repository = "https://github.com/yourusername/abop-iced"
readme = "README.md"
keywords = ["audio", "audiobook", "processing", "iced", "gui"]
categories = ["multimedia::audio", "gui", "command-line-utilities"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.bench]
opt-level = 3
lto = true
codegen-units = 1
debug = true
