[workspace]
members = [
    "abop-core",
    "abop-gui",
    "abop-cli"
]
resolver = "2"

[workspace.dependencies]
# Critical dependencies with pinned versions
iced = { version = "0.13.1", features = ["tokio", "advanced"] }

# Other dependencies with caret versioning
tokio = { version = "^1", features = ["full"] }
tokio-util = { version = "^0.7", features = ["sync"] }
tokio-stream = "^0.1"
futures = "^0.3"
async-trait = "^0.1"
humantime-serde = "^1.1"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
chrono = { version = "^0.4", features = ["serde"] }
uuid = { version = "^1", features = ["v4", "serde"] }
thiserror = "^1"
anyhow = "^1"
log = "^0.4"
tracing = "^0.1"
tracing-subscriber = { version = "^0.3", features = ["env-filter"] }
walkdir = "^2"
id3 = "^1"
mp4ameta = "^0.4"
rusqlite = { version = "0.31", features = ["bundled"] }
lru = "^0.12"
num_cpus = "^1"
tempfile = "^3"
tokio-test = "^0.4"
toml = "^0.8"
once_cell = "^1"
bitflags = "^2"
cfg_aliases = "^0.1"
fontdb = "^0.16"
getrandom = "^0.2"
hashbrown = "^0.14"
kurbo = "^0.9"
libloading = "^0.8"
dirs = "^5"
r2d2 = "^0.8"
r2d2_sqlite = "^0.24"
symphonia = "^0.5"
rodio = "^0.17"
num-complex = "^0.4"
hound = "^3"
rayon = "^1"
bytemuck = "^1"
rand = "^0.8"
rfd = "^0.14"

[workspace.lints.clippy]
# Promote important lints to warnings (keeping best practices)
missing_errors_doc = "warn"
missing_panics_doc = "warn"
must_use_candidate = "warn"
doc_markdown = "warn"
float_cmp = "warn"
cast_precision_loss = "warn"
cast_possible_truncation = "warn"
cast_sign_loss = "warn"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Your Name <your.email@example.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/yourusername/abop"
description = "A modern, efficient audiobook management system built with Rust and Iced"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 0
debug = true

[profile.test]
opt-level = 0
debug = true

[profile.bench]
opt-level = 3
debug = false
lto = true
codegen-units = 1
