[package]
name = "abop-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Core functionality for ABOP - Audiobook Organizer & Processor"
license.workspace = true
repository.workspace = true

[features]
default = []
bench = ["simd"]  # Enable benchmarking features
simd = []  # Enable SIMD optimizations where available

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "doc_cfg"]

[dependencies]
# Workspace dependencies
thiserror.workspace = true
log.workspace = true
tracing.workspace = true
serde.workspace = true
toml.workspace = true
chrono.workspace = true
uuid.workspace = true
once_cell.workspace = true

# Common dependencies
bitflags.workspace = true
cfg_aliases.workspace = true
fontdb.workspace = true
getrandom.workspace = true
hashbrown.workspace = true
kurbo.workspace = true
libloading.workspace = true

# File System & Database
dirs.workspace = true
walkdir.workspace = true
rusqlite.workspace = true
r2d2.workspace = true
r2d2_sqlite.workspace = true

# Audio Processing
symphonia.workspace = true
rodio.workspace = true
num-complex.workspace = true
hound.workspace = true
rayon.workspace = true
bytemuck.workspace = true
rand.workspace = true
serde_json.workspace = true

# Async
iced = { version = "0.13.1", features = ["tokio", "advanced"] }
tokio.workspace = true
futures.workspace = true
async-trait.workspace = true
humantime-serde.workspace = true
tokio-util.workspace = true
tokio-stream.workspace = true

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
tempfile.workspace = true
approx = "0.5.1"  # For floating-point comparisons in tests
